package com.chattyhive.backend.contentprovider.formats;

/**
 * Created by Jonathan on 23/06/2014.
 */
public enum Formats {
    /*
     * RESPONSE FORMATS
     */
    COMMON_RESPONSE,
    LOCAL_USER_PROFILE_RESPONSE,
    ANONYMOUS_USER_RESPONSE,
    PRIVATE_USER_RESPONSE,
    HIVE_RESPONSE,
    HIVE_ID_RESPONSE,
    ANONYMOUS_CHAT_INFO_RESPONSE,
    MESSAGE_RESPONSE,
    MESSAGE_CONTENT_RESPONSE,
    MESSAGE_RECEIVED_RESPONSE,
    MESSAGE_COUNT_RESPONSE,
    LAST_MESSAGE_RESPONSE,
    CHAT_SYNC_RESPONSE,
    USER_CHATS_RESPONSE,
    /*
     * REQUEST FORMATS
     */
    USER_ID_REQUEST,
    USER_PROFILE_REQUEST,
    LOGIN_REQUEST,
    HIVE_ID_REQUEST,
    CHAT_ID_REQUEST,
    MESSAGE_REQUEST,
    MESSAGE_ID_REQUEST,
    MESSAGE_INTERVAL_REQUEST,
    MESSAGE_SPAN_REQUEST,
    MESSAGE_CONTENT_REQUEST
}
